config =  [[['1Hat', 'BLANK.PNG', 5.65],
  ['1Hat', 'Blue- Woolhat.PNG', 5.55],
  ['1Hat', 'Bobagen.PNG', 5.55],
  ['1Hat', 'Dark Pink - Woolhat.PNG', 5.55],
  ['1Hat', 'Green - Puichii Turban .PNG', 5.55],
  ['1Hat', 'Green - Woolhat.PNG', 5.55],
  ['1Hat', 'IK - Wig.PNG', 5.55],
  ['1Hat', 'Monad hat.PNG', 5.55],
  ['1Hat', 'Monhat.PNG', 5.55],
  ['1Hat', 'NPC1.PNG', 5.55],
  ['1Hat', 'NPC2.PNG', 5.55],
  ['1Hat', 'Orange - Wig.PNG', 5.55],
  ['1Hat', 'Orange Ik - Wig.PNG', 5.55],
  ['1Hat', 'Purple - Woolhat.PNG', 5.55],
  ['1Hat', 'Salmonad Soup.PNG', 5.55],
  ['1Hat', 'White - Wig.PNG', 5.55],
  ['1Hat', 'Yellow - Puichii Turban.PNG', 5.55],
  ['1Hat', 'Yellow - Wig.PNG', 5.55]],
 [['2Hand', 'Blue Boxing Gloves.PNG', 5.4],
  ['2Hand', 'Green - Ribbon Boxing Gloves.PNG', 4.3],
  ['2Hand', 'Green - flower Boxing Gloves(1).PNG', 4.3],
  ['2Hand', 'Green - flower Boxing Gloves.PNG', 4.3],
  ['2Hand', 'Green Boxing Gloves.PNG', 4.3],
  ['2Hand', 'Light pink- Twotone Boxing Gloves.PNG', 4.3],
  ['2Hand', 'Orange - Ribbon Boxing Gloves.PNG', 4.3],
  ['2Hand', 'Pink - Blue Boxing Gloves.PNG', 4.3],
  ['2Hand', 'Pink - Flower Boxing Gloves.PNG', 4.3],
  ['2Hand', 'Pink - Ribbon Boxing Gloves.PNG', 4.3],
  ['2Hand', 'Pink - Twotone Boxing Gloves(1).PNG', 4.3],
  ['2Hand', 'Pink - Twotone Boxing Gloves.PNG', 4.3],
  ['2Hand', 'Pink Boxing Gloves.PNG', 4.3],
  ['2Hand', 'Purple - Ribbon Boxing Gloves.PNG', 4.3],
  ['2Hand', 'Purple - Twotone Boxing Gloves.PNG', 4.3],
  ['2Hand', 'Purple Boxing Gloves.PNG', 4.3],
  ['2Hand', 'Red - Ribbon Boxing Gloves.PNG', 4.3],
  ['2Hand', 'Red - Twotone Boxing Gloves(1).PNG', 4.3],
  ['2Hand', 'Red - Twotone Boxing Gloves.PNG', 4.3],
  ['2Hand', 'Red Boxing Gloves.PNG', 4.3],
  ['2Hand', 'White - Twotone Boxing Gloves.PNG', 4.3],
  ['2Hand', 'Yellow - flower Boxing Gloves.PNG', 4.3],
  ['2Hand', 'Yellow Boxing Gloves.PNG', 4.3]],
 [['3Foot', 'Black - Boots.PNG', 6.25],
  ['3Foot', 'Blue - Changdao Flipflop.PNG', 6.25],
  ['3Foot', 'Brown - Boots.PNG', 6.25],
  ['3Foot', 'Brown - Work shoes.PNG', 6.25],
  ['3Foot', 'Gray - Work shoes.PNG', 6.25],
  ['3Foot', 'Green - Work shoes.PNG', 6.25],
  ['3Foot', 'Light Brown- Boots.PNG', 6.25],
  ['3Foot', 'Pink - Boots.PNG', 6.25],
  ['3Foot', 'Pink - Changdao Flipflop.PNG', 6.25],
  ['3Foot', 'Pink - Flower - Changdao Flipflop.PNG', 6.25],
  ['3Foot', 'Purple - Changdao Flipflop.PNG', 6.25],
  ['3Foot', 'Purple - Flower - Changdao Flipflop.PNG', 6.25],
  ['3Foot', 'Red - Changdao Flipflop.PNG', 6.25],
  ['3Foot', 'Twotone - Flower - Changdao Flipflop(1).PNG', 6.25],
  ['3Foot', 'Twotone - Flower - Changdao Flipflop.PNG', 6.25],
  ['3Foot', 'Twotone- Changdao Flipflop.PNG', 6.25]],
 [['4Body', 'Gray - Moncock.PNG', 12.5],
  ['4Body', 'Green - Moncock.PNG', 12.5],
  ['4Body', 'Light purple - Moncock.PNG', 12.5],
  ['4Body', 'Orange - Moncock.PNG', 12.5],
  ['4Body', 'Original - Moncock.PNG', 12.5],
  ['4Body', 'Purple - Moncock.PNG', 12.5],
  ['4Body', 'Red - Moncock.PNG', 12.5],
  ['4Body', 'Yellow - Moncock.PNG', 12.5]],
 [['5BG', 'Dark Pink - BG.PNG', 7.72],
  ['5BG', 'Deep blue - BG.PNG', 7.69],
  ['5BG', 'Gray Purple - BG.PNG', 7.69],
  ['5BG', 'Green - BG.PNG', 7.69],
  ['5BG', 'IMG_0993.PNG', 7.69],
  ['5BG', 'Orange - BG.PNG', 7.69],
  ['5BG', 'Pastel Blue - BG.PNG', 7.69],
  ['5BG', 'Pastel Green - BG.PNG', 7.69],
  ['5BG', 'Pastel purple - BG.PNG', 7.69],
  ['5BG', 'Pink - BG.PNG', 7.69],
  ['5BG', 'Purple - BG(1).PNG', 7.69],
  ['5BG', 'Purple - BG.PNG', 7.69],
  ['5BG', 'Red - BG.PNG', 7.69]]]
