title = "Moncock Sample"
desc  = "We are Moncock"
trait_types = [
    'Hat',
    'Hand',
    'Foot',
    'Body',
    'Background',
]
trait_mapper = {
    'BLANK.PNG'                         : 'None',
    'Black - Boots.PNG'                 : 'Black Boots',
    'Blue - Changdao Flipflop.PNG'      : 'Blue Changdao Flipflop',
    'Blue Boxing Gloves.PNG'            : 'Blue Boxing Gloves',
    'Blue- Woolhat.PNG'                 : 'Blue Woolhat',
    'Bobagen.PNG'                       : 'Bobagen',
    'Brown - Boots.PNG'                 : 'Brown Boots',
    'Brown - Work shoes.PNG'            : 'Brown Work Shoes',
    'Dark Pink - BG.PNG'                : 'Dark Pink',
    'Dark Pink - Woolhat.PNG'           : 'Dark Pink Woolhat',
    'Deep blue - BG.PNG'                : 'Deep Blue',
    'Gray - Moncock.PNG'                : 'Gray',
    'Gray - Work shoes.PNG'             : 'Gray Work Shoes',
    'Gray Purple - BG.PNG'              : 'Gray Purple',
    'Green - BG.PNG'                    : 'Green',
    'Green - Moncock.PNG'               : 'Green',
    'Green - Puichii Turban .PNG'       : 'Green Puichii Turban',
    'Green - Ribbon Boxing Gloves.PNG'  : 'Green Ribbon Boxing Gloves',
    'Green - Woolhat.PNG'               : 'Green Woolhat',
    'Green - Work shoes.PNG'            : 'Green Work Shoes',
    'Green - flower Boxing Gloves(1).PNG': 'Green Flower Boxing Gloves',
    'Green - flower Boxing Gloves.PNG'  : 'Green Flower Boxing Gloves',
    'Green Boxing Gloves.PNG'           : 'Green Boxing Gloves',
    'IK - Wig.PNG'                      : 'IK Wig',
    'IMG_0993.PNG'                      : 'Purple Pink',
    'Light Brown- Boots.PNG'            : 'Light Brown Boots',
    'Light pink- Twotone Boxing Gloves.PNG': 'Light Pink Two-Tone Boxing Gloves',
    'Light purple - Moncock.PNG'        : 'Light Purple',
    'Monad hat.PNG'                     : 'Monad Hat',
    'Monhat.PNG'                        : 'Monhat',
    'NPC1.PNG'                          : 'NPC',
    'NPC2.PNG'                          : 'NPC',
    'Orange - BG.PNG'                   : 'Orange',
    'Orange - Moncock.PNG'              : 'Orange',
    'Orange - Ribbon Boxing Gloves.PNG' : 'Orange Ribbon Boxing Gloves',
    'Orange - Wig.PNG'                  : 'Orange Wig',
    'Orange Ik - Wig.PNG'               : 'Orange IK Wig',
    'Original - Moncock.PNG'            : 'Original',
    'Pastel Blue - BG.PNG'              : 'Pastel Blue',
    'Pastel Green - BG.PNG'             : 'Pastel Green',
    'Pastel purple - BG.PNG'            : 'Pastel Purple',
    'Pink - BG.PNG'                     : 'Pink',
    'Pink - Blue Boxing Gloves.PNG'     : 'Pink Blue Boxing Gloves',
    'Pink - Boots.PNG'                  : 'Pink Boots',
    'Pink - Changdao Flipflop.PNG'      : 'Pink Changdao Flipflop',
    'Pink - Flower - Changdao Flipflop.PNG': 'Pink Flower Changdao Flipflop',
    'Pink - Flower Boxing Gloves.PNG'   : 'Pink Flower Boxing Gloves',
    'Pink - Ribbon Boxing Gloves.PNG'   : 'Pink Ribbon Boxing Gloves',
    'Pink - Twotone Boxing Gloves(1).PNG': 'Pink Two-Tone Boxing Gloves',
    'Pink - Twotone Boxing Gloves.PNG'  : 'Pink Two-Tone Boxing Gloves',
    'Pink Boxing Gloves.PNG'            : 'Pink Boxing Gloves',
    'Purple - BG(1).PNG'                : 'Purple',
    'Purple - BG.PNG'                   : 'Purple',
    'Purple - Changdao Flipflop.PNG'    : 'Purple Changdao Flipflop',
    'Purple - Flower - Changdao Flipflop.PNG': 'Purple Flower Changdao Flipflop',
    'Purple - Moncock.PNG'              : 'Purple',
    'Purple - Ribbon Boxing Gloves.PNG' : 'Purple Ribbon Boxing Gloves',
    'Purple - Twotone Boxing Gloves.PNG': 'Purple Two-Tone Boxing Gloves',
    'Purple - Woolhat.PNG'              : 'Purple Woolhat',
    'Purple Boxing Gloves.PNG'          : 'Purple Boxing Gloves',
    'Red - BG.PNG'                      : 'Red',
    'Red - Changdao Flipflop.PNG'       : 'Red Changdao Flipflop',
    'Red - Moncock.PNG'                 : 'Red',
    'Red - Ribbon Boxing Gloves.PNG'    : 'Red Ribbon Boxing Gloves',
    'Red - Twotone Boxing Gloves(1).PNG': 'Red Two-Tone Boxing Gloves',
    'Red - Twotone Boxing Gloves.PNG'   : 'Red Two-Tone Boxing Gloves',
    'Red Boxing Gloves.PNG'             : 'Red Boxing Gloves',
    'Salmonad Soup.PNG'                 : 'Salmonad Soup',
    'Twotone - Flower - Changdao Flipflop(1).PNG': 'Two-Tone Flower Changdao Flipflop',
    'Twotone - Flower - Changdao Flipflop.PNG': 'Blue Flower Changedao Flipflop',
    'Twotone- Changdao Flipflop.PNG'    : 'Two-Tone Changdao Flipflop',
    'White - Twotone Boxing Gloves.PNG' : 'White Two-Tone Boxing Gloves',
    'White - Wig.PNG'                   : 'White Wig',
    'Yellow - Moncock.PNG'              : 'Yellow',
    'Yellow - Puichii Turban.PNG'       : 'Yellow Puichii Turban',
    'Yellow - Wig.PNG'                  : 'Yello Wig',
    'Yellow - flower Boxing Gloves.PNG' : 'Yellow Flower Boxing Gloves',
    'Yellow Boxing Gloves.PNG'          : 'Yellow Boxing Gloves',
}
